config/routes.rb
Gitstud::Application.routes.draw do

  root  :to=>'main#index'
  resources :main ,:only => [] do
    collection do
      get :sign
      get :sign_out
      post :sign_in
      post :sign_up
    end
  end

  resources :student ,:only =>[] do
    collection do
      get :repositories
      get :assignments
      get :dashboard
    end
  end

  resources :instructor , :only=>[] do
    collection do
      get :assignments
      get :dashboard
    end
  end

  resources :assignment do
      resources :repository do
        member do
        post :add_students
      end
        get "/tree/:ref/*id" =>"tree#show"
        get "/tree/:ref" =>"tree#show"
        get("/commits/:ref/*id",:to=>"commits#index",:constraints=>{ id: /.+/, format: false})
        get "/commits/:ref" =>"commits#index"
        get "/commit/:id" =>"commits#show"
                  get(
            '/blob/:ref/*id',
            to: 'blob#show',
            constraints: { id: /.+/, format: false },
          )
      end
    member do
      get :assignment_repositories
    end
  end

end

app/models/student.rb
class Student
  include Mongoid::Document
      has_one :user, :as => :student_or_instructor, :dependent => :destroy
      has_and_belongs_to_many :repositories
      has_and_belongs_to_many :instructors
      
      def username
      	user.username
      end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
	layout "inner_layout"
	def dashboard
		@repositories=@user.student_or_instructor.repositories
		@assignments=Assignment.all
		#log_file_name = '/var/gitfiles/qais'
		#unless File.exist?(log_file_name)
	#		Delayed::Job.enqueue(CreateRepository.new(log_file_name))
	#	end
	end

	def repositories
		@repositories=@user.student_or_instructor.repositories
	end

	def assignments
	end


end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/dashboard.html.erb
<div class="panel">
                      <div class="panel-heading">
                          
                          <h3 class="panel-title">Assignments</h3>
                      </div>
          
                      <div class="panel-body">
                          <div class="table-responsive">
                              <table class="table table-hover">
                                  <thead>
                                      <tr>
                                          <th style="width:6ex">Course</th>
                                          <th>Name</th>
                                          <th>Date</th>
                                          <th class="text-center">Description</th>
                                          <th class="text-right">Actions</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    <%@assignments.each do |ass|%>
                                      <tr>
                                          <td><%=ass.course_name%></td>
                                          <td><%=ass.name%></td>
                                          <td><%=ass.due_date%></td>
                                          <td class="text-center"><span class="label label-table label-success"><%=ass.description%></span></td>
                                          <td class="text-right">
                                            <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" href="<%=assignment_path(:id=>ass.id)%>" data-original-title="Show" data-container="body"><i class="fa fa-file"></i></a>
                                              <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" href="<%=new_assignment_repository_path(ass.id)%>" data-original-title="Repository" data-container="body"><i class="fa fa-plus"></i></a>
                                          </td>
                                      </tr>
                                      <%end%>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>  

app/views/student/repositories.html.erb
<div class="panel-body">
                          <div class="table-responsive">
<table class="table table-hover">
                                  <thead>
                                      <tr>
                                          <th>Repository Name</th>
                                          <th>Assignment Name</th>
                                          <th>due date</th>
                                          <th>up to</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    <% @repositories.each do |rep| %>
                                      <tr>
                                          <td><a href="<%=assignment_repository_path(:assignment_id=>rep.assignment.id,:id=>rep.name)%>"><%=rep.name%></a></td>
                                          <td><%=rep.assignment.name%></td>
                                          <td><%=rep.assignment.due_date%></td>
                                          <td><%=rep.assignment.up_to%></td>
                                      </tr>
                                      <%end%>
                                  </tbody>
                              </table>
                          </div></div>