config/routes.rb
Gitstud::Application.routes.draw do

  root  :to=>'main#index'
  resources :main ,:only => [] do
    collection do
      get :sign
      get :sign_out
      post :sign_in
      post :sign_up
    end
  end

  resources :student ,:only =>[] do
    collection do
      get :repositories
      get :assignments
      get :dashboard
    end
  end

  resources :instructor , :only=>[] do
    collection do
      get :assignments
      get :dashboard
    end
  end

  resources :assignment do
      resources :repository do
        member do
        post :add_students
      end
        get "/tree/:ref/*id" =>"tree#show"
        get "/tree/:ref" =>"tree#show"
        get("/commits/:ref/*id",:to=>"commits#index",:constraints=>{ id: /.+/, format: false})
        get "/commits/:ref" =>"commits#index"
        get "/commit/:id" =>"commits#show"
                  get(
            '/blob/:ref/*id',
            to: 'blob#show',
            constraints: { id: /.+/, format: false },
          )
      end
    member do
      get :assignment_repositories
    end
  end

end

app/models/assignment.rb
class Assignment
  include Mongoid::Document
  belongs_to :instructor
  has_many :repositories

  field :name
  field :description
  field :due_date
  field :up_to
  field :mark
  field :course_name
  field :course_id


end

app/controllers/assignment_controller.rb
class AssignmentController < ApplicationController
      layout "inner_layout"

	def index
	end

	def new
		@assignment=@current_instructor.assignments.new
	end

	def create
		if params[:assignment]
			params.permit!
			@assignment=@current_instructor.assignments.create(params[:assignment])
			if @assignment.save!
			redirect_to dashboard_instructor_index_path,:flash => { :success => "Created assignment" }
			end
		end
	end

	def show
		@assignment=Assignment.find(params[:id])
	end

	def edit
		@assignment=@current_instructor.assignments.find(params[:id])
	end

	def update
		@assignment=@current_instructor.assignments.find(params[:id])
		if params[:assignment]
			params.permit!
		if @assignment.update(params[:assignment])
			redirect_to dashboard_instructor_index_path,:flash => { :success => "Edited assignment" }
		end
		end
	end

	def destroy
		assignment=@current_instructor.assignments.find(params[:id])
		assignment.destroy
    	flash[:alert]= "assignment was deleted"
    	redirect_to dashboard_instructor_index_path
	end

	def assignment_repositories
		@assignment=Assignment.find(params[:id])
		@repositories=@assignment.repositories
	end

end

app/helpers/assignment_helper.rb
module AssignmentHelper
end

app/views/assignment/assignment_repositories.html.erb
 <table class="table table-hover">
                                  <thead>
                                      <tr>
                                          <th>Repository Name</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    <%@repositories.each do |repo|%>
                                      <tr>
                                        
                                          <td><a href="<%=assignment_repository_path(:assignment_id=>repo.assignment.id,:id=>repo.name)%>"><%=repo.name%></a></td>
                                        
                                      </tr>
                                    
                                      <%end%>
                                  </tbody>
                              </table>

app/views/assignment/edit.html.erb
<div class="text-center">
  <h1 style="padding-bottom:23px;">Editing assignment</h1>
  </div>

<div class="Sign_Form col-lg-6 col-lg-offset-3 ">

<%= form_for(@assignment, :url => assignment_path(:id=>@assignment)) do |f| %>

   
    <%= f.text_field :name,:class=>"form-control", :required=>"true", :placeholder=>"Name" %>
  <br />
   <%= f.text_area :description,:class=>"form-control", :required=>"true", :placeholder=>"Description" %>
  <br />
   <%= f.text_field :due_date,:class=>"form-control", :required=>"true", :placeholder=>"due_date" %>
  <br />
  <%= f.number_field :mark,:class=>"form-control", :required=>"true", :placeholder=>"mark" %>
  <br />
  <%= f.number_field :up_to,:class=>"form-control", :required=>"true", :placeholder=>"up_to" %>
  <br />
   <%= f.text_field :course_name,:class=>"form-control", :required=>"true", :placeholder=>"course_name" %>
  <br />
  <%= f.number_field :course_id,:class=>"form-control", :required=>"true", :placeholder=>"course_id" %>
  <br />

  <div class="actions text-center">
    <div style="margin-top:20px;">
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to "Cancel" ,request.referer, :class=>"btn btn-info",:style=>"    margin-left: 10px;" %>
</div>
  </div>
<% end %>
</div>

app/views/assignment/new.html.erb
<div class="text-center">
  <h1 style="padding-bottom:23px;">create assignment</h1>
</div>

<div class="Sign_Form col-lg-6 col-lg-offset-3 ">
<%= form_for(@assignment,:url=>assignment_index_path) do |f|%>

    <%= f.text_field :name,:class=>"form-control", :required=>"true", :placeholder=>"Name" %>
  <br />
   <%= f.text_area :description,:class=>"form-control", :required=>"true", :placeholder=>"Description" %>
  <br />
   <%= f.date_field :due_date,:class=>"form-control", :required=>"true", :placeholder=>"due_date" %>
  <br />
  <%= f.number_field :mark,:class=>"form-control", :required=>"true", :placeholder=>"mark" %>
  <br />
  <%= f.number_field :up_to,:class=>"form-control", :required=>"true", :placeholder=>"up_to" %>
  <br />
  <%= f.select :course_name, 
 [['OS','OS'],
 ['Network','Network'],
 ['Software Design','Software Design'],
 ['Wireless','Wireless'],
 ['Database','Database'],
 ['OOP','OOP'],
  ], {:include_blank=>"-- select course --"},{:class=>"form-control"} %>
  <br />
  

  <div class="actions text-center">
    <div style="margin-top:20px;">
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to "Cancel" ,request.referer, :class=>"btn btn-info",:style=>"    margin-left: 10px;" %>
</div>
  </div>
<% end %>
</div>

app/views/assignment/show.html.erb
<div class="boxed-group editzone">
    <h3><%=@assignment.name%></h3>
<div class="boxed-group-inner">
		<label>Assignment description :</label>
			<p><%=@assignment.description%></p>
		<label>Due date :</label>
			<p><%=@assignment.due_date%></p>
		<label>Team up-to :</label>
			<p><%=@assignment.up_to%></p>
		<label>Mark :</label>
			<p><%=@assignment.mark%></p>
		<label>Course name :</label>
			<p><%=@assignment.course_name%></p>
</div>
</div>
									

<style type="text/css">
.boxed-group {
  position: relative;
  border-radius: 3px;
  margin-bottom: 30px}

.boxed-group.editzone>h3 {
  background-color: #f5f5f5;
  border: 1px solid #d8d8d8;
  color: #333;
  padding: 9px 10px 10px;
  font-size: 14px;
  line-height: 17px;
  text-shadow: none;}

  .boxed-group-inner {
  padding: 15px 10px;
  background: #fff;
  margin-top: -10px;
  border: 1px solid #d8d8d8;
  border-bottom-left-radius: 3px;
  border-bottom-right-radius: 3px;
  color: #666;
  font-size: 13px;
  }

</style>