config/routes.rb
Gitstud::Application.routes.draw do

  root  :to=>'main#index'
  resources :main ,:only => [] do
    collection do
      get :sign
      get :sign_out
      post :sign_in
      post :sign_up
    end
  end

  resources :student ,:only =>[] do
    collection do
      get :repositories
      get :assignments
      get :dashboard
    end
  end

  resources :instructor , :only=>[] do
    collection do
      get :assignments
      get :dashboard
    end
  end

  resources :assignment do
      resources :repository do
        member do
        post :add_students
      end
        get "/tree/:ref/*id" =>"tree#show"
        get "/tree/:ref" =>"tree#show"
        get("/commits/:ref/*id",:to=>"commits#index",:constraints=>{ id: /.+/, format: false})
        get "/commits/:ref" =>"commits#index"
        get "/commit/:id" =>"commits#show"
                  get(
            '/blob/:ref/*id',
            to: 'blob#show',
            constraints: { id: /.+/, format: false },
          )
      end
    member do
      get :assignment_repositories
    end
  end

end

app/models/repository.rb
class Repository
  include Mongoid::Document

  has_and_belongs_to_many :students
  #has_many :files
  belongs_to :assignment

  field :url
  field :name
  field :super_std

end

app/controllers/repository_controller.rb
class RepositoryController < ApplicationController
layout "inner_layout"
	before_filter :load_repository , :only=>[:show,:edit,:add_students]


	def load_repository
		 	if @repo=Repository.where(:name=>params[:id]).last
				@repository=Gitlab::Git::Repository.new("/repositories/#{@repo.name}.git")
			end
	end

	def index

	end

	def new
		@repository=Repository.new
	end

	def create
		@assignment=Assignment.find(params[:assignment_id])
		params.permit!
		params[:repository][:name].gsub!(" ","_")
		params[:repository][:name].gsub!("\n","_")
		my_project=	params[:repository][:name]
		@repository=@assignment.repositories.new(url:params[:repository][:name],name:params[:repository][:name],:super_std=>@current_student.id)
		@repository.students << @current_student
		@current_student.repositories << @repository
		@assignment.repositories.new
		if @repository.save! && @current_student.save!
		system "sudo mkdir /repositories/#{my_project}.git && cd /repositories/#{my_project}.git && sudo git init --bare --share"
		system "sudo git clone /repositories/#{my_project}.git /first_commit/#{my_project}  && cd /first_commit/#{my_project} && sudo touch README.txt && sudo git add . && sudo git commit -m 'Initial commit' && sudo git push origin master"
		redirect_to assignment_repository_path(:assignment_id=>@assignment.id,:id=>@repository.name),:flash => { :success => "Repository created" } and return
		end
	end

	def show
		@assignment=Assignment.find(params[:assignment_id])
		@tree= Gitlab::Git::Tree.where(@repository,"master","")
	end

	def add_students
		@repo.students << Student.where(:_id=>params[:student_ids]).last
		@repo.save!
		@assignment=Assignment.find(params[:assignment_id])
		redirect_to assignment_repository_path(:assignment_id=>@assignment.id,:id=>@repo.name),:flash => { :success => "Student added" } and return

	end

	def edit
	end

	def update
	end

	def destroy
		repository=Repository.find(params[:id])
		repository.destroy
    	flash[:alert]= "repository was deleted"
    	redirect_to redirect_to dashboard_student_index_path
	end

	
end

app/helpers/repository_helper.rb
module RepositoryHelper
end

app/views/repository/new.html.erb
<div class="admin-form col-lg-6 col-lg-offset-3 ">
  <div class="text-center">
  <h1 style="padding-bottom:23px;">create repository</h1>
</div>
<%= form_for(@repository,:url=>assignment_repository_index_path(params[:assignment_id])) do |f|%>

    <%= f.text_field :name,:class=>"form-control", :required=>"true", :placeholder=>"Name", :id=>"name" %>
  <br />
   <%= f.hidden_field :url,:class=>"form-control",:id=>"url"%>
   <br />
   

  <div class="actions text-center">
    <div style="margin-top:20px;">
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to "Cancel" ,request.referer, :class=>"btn btn-info",:style=>"    margin-left: 10px;" %>
</div>
  </div>
<% end %>
</div>
<style type="text/css">
.admin-form {
    line-height: 1.231;
    font-weight: 400;
    font-size: 14px;
    padding-bottom: 40px;
    padding-top: 28px;
    color: #FFFFFF;
    background-color: #48687D;
}
</style>

<script type="text/javascript">
$(document).ready(function(){
  
  $('#name').blur(function(){
      var value= $(this).val();
      var uri;
      uri= value.replace(" ","");
      uri= uri.replace(".","");
      uri= uri.replace("/","");
      uri= uri.replace(",","");
      uri= uri.replace("'","");
      uri= uri.replace("\"","");
      uri= uri.replace("=","");
      uri= uri.replace("?=","");
      $('#url').val(uri);
  });
});
</script>

app/views/repository/show.html.erb
<div class="row">
<div class="col-md-8">
	<div class="boxed-group editzone">
    <div class="panel-heading" style="background-color:#202d3b;
                   color: #fff;">
                    <h4 class="panel-title">
                        Repository
                        
                     <span class="pull-right">
                      <a class="btn btn-xs" href="/assignment/<%=@assignment.id%>/repository/<%=@repo.name%>/commits/<%= params[:ref].nil? ? 'master' : params[:ref] rescue 'master' %>" data-placement="bottom" data-toggle="tooltip" data-original-title="commits"><i class="fa fa-bars" style="font-size: 20px;color:#fff;margin-top: 0px;"></i>
                        </a>

                        <a class="btn btn-xs" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Contributors"><i class="fa fa-users" style="font-size: 20px;color:#fff;margin-top: 0px;"></i>
                        </a>
                        </span>
                    </h4>
                  </div>
	<div class="boxed-group-inner">
<% @tree.each do |x| %>
<% if x.type==:blob %>
<li style="list-style-type:none;"> <i class="fa fa-file" style="color:#0dc0c0;padding-right:5px;"> </i> <a href="/assignment/<%= @assignment.id %>/repository/<%= params[:id]%>/blob/<%= params[:ref].nil? ? 'master' : params[:ref] rescue 'master' %>/<%= x.path %>"><%=x.name%></a></li>
<% else %>
<li style="list-style-type:none;"> <i class="fa fa-folder" style="color:#0dc0c0;padding-right:5px;"> </i> <a href="/assignment/<%= @assignment.id %>/repository/<%= params[:id]%>/tree/<%= params[:ref].nil? ? 'master' : params[:ref] rescue 'master' %>/<%= x.path %>"><%=x.name%></a></li>
<% end %>
<% end %>
</div>
</div>
</div>

<%if @user %>
<%if @user.student_or_instructor_type=="Student"%>
<div class="col-md-4">
<div class="boxed-group editzone">
		<h3>Add Students</h3>
	<div class="boxed-group-inner">
<% if @assignment.up_to.to_i > @repo.students.count %>

	<%= form_for(Repository.new,:url=>add_students_assignment_repository_path(:assignment_id=>params[:assignment_id],:id=>params[:id]),:class=>"form-inline") do |f|%>

	   <%= select_tag :student_ids,
    options_from_collection_for_select(Student.where(:_id.ne=>@current_student.id,:repository_ids.nin=>[@repo.id]), :id, :username), :class => "chzn-select",:style=>"width:208px;",:placeholder=>"awe", :id=>"signup-target-lang" ,:required=>true %>
    	<%= f.submit 'Add' ,:class=>"btn btn-block btn-success" %>
	<% end %>
	<% end %>
</div>
</div>
</div>
</div>

<div class="col-md-4 col-md-offset-8">
<div class="boxed-group editzone">
    <h3>Delete repository</h3>
  <div class="boxed-group-inner">
    <%= link_to " Delete Repository",assignment_repository_path,:method=>"get",:class=>"btn btn-block btn-danger", :data=>{:placement=>"bottom",:confirm=>"Once you delete your repository there's no going back. Are you sure?", :toggle=>"tooltip", :title=>"delete"} %>
  </div>
  </div>
  </div>
  <%end%>
  <%end%>

<script type="text/javascript">
$(".chzn-select").chosen();
</script>

<style type="text/css">
.boxed-group {
  position: relative;
  border-radius: 3px;
  margin-bottom: 30px}

.boxed-group.editzone>h3 {
  background-color: #f5f5f5;
  border: 1px solid #d8d8d8;
  color: #333;
  padding: 9px 10px 10px;
  font-size: 14px;
  line-height: 17px;
  text-shadow: none;}

  .boxed-group-inner {
  padding: 15px 10px;
  background: #fff;
  margin-top: -10px;
  border: 1px solid #d8d8d8;
  border-bottom-left-radius: 3px;
  border-bottom-right-radius: 3px;
  color: #666;
  font-size: 13px;
  }


</style>