config/routes.rb
Gitstud::Application.routes.draw do

  root  :to=>'main#index'
  resources :main ,:only => [] do
    collection do
      get :sign
      get :sign_out
      post :sign_in
      post :sign_up
    end
  end

  resources :student ,:only =>[] do
    collection do
      get :repositories
      get :assignments
      get :dashboard
    end
  end

  resources :instructor , :only=>[] do
    collection do
      get :assignments
      get :dashboard
    end
  end

  resources :assignment do
      resources :repository do
        member do
        post :add_students
      end
        get "/tree/:ref/*id" =>"tree#show"
        get "/tree/:ref" =>"tree#show"
        get("/commits/:ref/*id",:to=>"commits#index",:constraints=>{ id: /.+/, format: false})
        get "/commits/:ref" =>"commits#index"
        get "/commit/:id" =>"commits#show"
                  get(
            '/blob/:ref/*id',
            to: 'blob#show',
            constraints: { id: /.+/, format: false },
          )
      end
    member do
      get :assignment_repositories
    end
  end

end

app/models/instructor.rb
class Instructor
  include Mongoid::Document
    has_one :user, :as => :student_or_instructor, :dependent => :destroy
    has_and_belongs_to_many :students
    has_many :assignments
    
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
	layout "inner_layout"

	def dashboard
		@assignments=@current_instructor.assignments
	end

	def assignments
	end

	
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/views/instructor/dashboard.html.erb
<div class="col-md-12">
<div class="panel">
                      <div class="panel-heading">
                          <div class="panel-control">
                              <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Information</h4><p style='width:150px'>This is an information bubble to help the user.</p>" data-html="true" title=""></a>
                          </div>
                          <h3 class="panel-title">Assignments</h3>
                      </div>
          
                      <div class="panel-body">
                          <div class="form-inline">
                              <div class="row">
                                  <div class="col-sm-6 table-toolbar-left">
                                    <a href="<%=new_assignment_path%>">
                                      <button id="demo-btn-addrow" class="btn btn-purple btn-labeled fa fa-plus">Add</button>
                                      </a>
                                  </div>
                                  
                              </div>
                          </div>
                          <div class="table-responsive">
                              <table class="table table-hover">
                                  <thead>
                                      <tr>
                                          <th style="width:6ex">Course</th>
                                          <th>Name</th>
                                          <th>Date</th>
                                          <th class="text-center">Description</th>
                                          <th class="text-right">Actions</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                    <%@assignments.each do |ass|%>
                                      <tr>
                                          <td><%=ass.course_name%></td>
                                          <td><%=ass.name%></td>
                                          <td><%=ass.due_date%></td>
                                          <td class="text-center"><span class="label label-table label-success"><%=ass.description%></span></td>
                                          <td class="text-right">
                                            <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" href="<%=assignment_repositories_assignment_path(:id=>ass.id)%>" data-original-title="Repositories" data-container="body"><i class="fa fa-file"></i></a>
                                              <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" href="<%=edit_assignment_path(:id=>ass.id)%>" data-original-title="Edit" data-container="body"><i class="fa fa-pencil"></i></a>
                                              <a class="btn btn-xs btn-default add-tooltip" data-toggle="tooltip" href="<%=assignment_path(:id=>ass.id)%>" data-original-title="Delete" data-container="body" data-confirm="Are you sure?" data-method="delete"><i class="fa fa-trash"></i></a>
                                          </td>
                                      </tr>
                                      <%end%>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>  </div> 